name: behapy
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - statsmodels
  - matplotlib
  - seaborn
  - intervaltree
  - bokeh==2.4.3
  - jupyter_bokeh
  - holoviews==1.15.4
  - datashader
  - pyarrow
  - bottleneck
  - pip:
    - tdt

